package com.nl.module.equipment

import com.nl.component.common.PropertyHelper

object ConstantUtils {

    fun randomEquipmentList(part: Int): MutableList<EquipmentVo> {
        return when (part) {
            EquipmentHelper.PART_WEAPON -> mutableListOf(
                EquipmentVo(
                    "普通长剑",
                    "1_normal/weapon.png",
                    500,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "精炼长剑",
                    "2_refine/weapon.png",
                    300,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "无瑕长剑",
                    "3_flawless/weapon.png",
                    200,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "非凡长剑",
                    "4_extraordinary/weapon.png",
                    100,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "至臻长剑",
                    "5_extreme/weapon.png",
                    100,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "绝世长剑",
                    "6_peerless/weapon.png",
                    100,
                    EquipmentHelper.PART_WEAPON
                )
            )
            EquipmentHelper.PART_CLOTHING -> mutableListOf(
                EquipmentVo(
                    "普通战甲",
                    "1_normal/clothing.png",
                    500,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "普通战甲",
                    "2_refine/clothing.png",
                    300,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "普通战甲",
                    "3_flawless/clothing.png",
                    200,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "普通战甲",
                    "4_extraordinary/clothing.png",
                    100,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "普通战甲",
                    "5_extreme/clothing.png",
                    100,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "普通战甲",
                    "6_peerless/clothing.png",
                    100,
                    EquipmentHelper.PART_CLOTHING
                )
            )
            EquipmentHelper.PART_ARMOR -> mutableListOf(
                EquipmentVo(
                    "恒河沙数盾",
                    "1_normal/armor.png",
                    300,
                    EquipmentHelper.PART_ARMOR
                ),
                EquipmentVo(
                    "锁子甲",
                    "2_refine/armor.png",
                    200,
                    EquipmentHelper.PART_ARMOR
                ),
                EquipmentVo(
                    "荆棘甲",
                    "3_flawless/armor.png",
                    150,
                    EquipmentHelper.PART_ARMOR
                ),
                EquipmentVo(
                    "碧落道袍",
                    "4_extraordinary/armor.png",
                    150,
                    EquipmentHelper.PART_ARMOR
                ),
                EquipmentVo(
                    "至臻战甲",
                    "5_extreme/armor.png",
                    150,
                    EquipmentHelper.PART_ARMOR
                ),
                EquipmentVo(
                    "绝世战甲",
                    "6_peerless/armor.png",
                    150,
                    EquipmentHelper.PART_ARMOR
                )
            )
            EquipmentHelper.PART_SHOES -> mutableListOf(
                EquipmentVo(
                    "闪电靴",
                    "1_normal/shoes.png",
                    200,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "潮生海落",
                    "2_refine/shoes.png",
                    300,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "屠戮战靴",
                    "3_flawless/shoes.png",
                    10,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "浮光掠影",
                    "4_extraordinary/shoes.png",
                    500,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "至臻战靴",
                    "5_extreme/shoes.png",
                    150,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "绝世战靴",
                    "6_peerless/shoes.png",
                    150,
                    EquipmentHelper.PART_SHOES
                )
            )
            EquipmentHelper.PART_RING -> mutableListOf(
                EquipmentVo(
                    "麻痹戒指",
                    "1_normal/ring.png",
                    200,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "永恒项链",
                    "2_refine/ring.png",
                    300,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "海上明月吊坠",
                    "3_flawless/ring.png",
                    10,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "勇者徽章",
                    "4_extraordinary/ring.png",
                    500,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "至臻戒指",
                    "5_extreme/ring.png",
                    150,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "绝世项链",
                    "6_peerless/ring.png",
                    150,
                    EquipmentHelper.PART_RING
                )
            )
            EquipmentHelper.PART_NECKLACE -> mutableListOf(
                EquipmentVo(
                    "麻痹项链",
                    "1_normal/necklace.png",
                    200,
                    EquipmentHelper.PART_NECKLACE
                ),
                EquipmentVo(
                    "永恒项链",
                    "2_refine/necklace.png",
                    300,
                    EquipmentHelper.PART_NECKLACE
                ),
                EquipmentVo(
                    "海上明月吊坠",
                    "3_flawless/necklace.png",
                    10,
                    EquipmentHelper.PART_NECKLACE
                ),
                EquipmentVo(
                    "勇者项链",
                    "4_extraordinary/necklace.png",
                    500,
                    EquipmentHelper.PART_NECKLACE
                ),
                EquipmentVo(
                    "至臻项链",
                    "5_extreme/necklace.png",
                    150,
                    EquipmentHelper.PART_NECKLACE
                ),
                EquipmentVo(
                    "绝世项链",
                    "6_peerless/necklace.png",
                    150,
                    EquipmentHelper.PART_NECKLACE
                )
            )
            else -> mutableListOf(
                EquipmentVo(
                    "一点黛眉刀",
                    "1_normal/weapon.png",
                    500,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "无量刀",
                    "1_normal/weapon.png",
                    300,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "劫灰剑",
                    "1_normal/weapon.png",
                    200,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "射日弓",
                    "1_normal/weapon.png",
                    100,
                    EquipmentHelper.PART_WEAPON
                ),
                EquipmentVo(
                    "恒河沙数盾",
                    "1_normal/weapon.png",
                    300,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "锁子甲",
                    "1_normal/weapon.png",
                    200,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "荆棘甲",
                    "1_normal/weapon.png",
                    150,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "碧落道袍",
                    "1_normal/weapon.png",
                    100,
                    EquipmentHelper.PART_CLOTHING
                ),
                EquipmentVo(
                    "闪电靴",
                    "1_normal/weapon.png",
                    200,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "潮生海落",
                    "1_normal/weapon.png",
                    300,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "屠戮战靴",
                    "1_normal/weapon.png",
                    10,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "浮光掠影",
                    "1_normal/weapon.png",
                    500,
                    EquipmentHelper.PART_SHOES
                ),
                EquipmentVo(
                    "麻痹戒指",
                    "1_normal/weapon.png",
                    200,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "永恒项链",
                    "1_normal/weapon.png",
                    300,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "海上明月吊坠",
                    "1_normal/weapon.png",
                    10,
                    EquipmentHelper.PART_RING
                ),
                EquipmentVo(
                    "勇者徽章",
                    "1_normal/weapon.png",
                    500,
                    EquipmentHelper.PART_RING
                )
            )
        }
    }

    fun randomEquipment(part: Int): EquipmentVo {
        return when (part) {
            EquipmentHelper.PART_CLOTHING -> {
                EquipmentVo(
                    "寂灭战甲",
                    "1_normal/clothing.png",
                    100,
                    EquipmentHelper.PART_CLOTHING,
                    "222222",
                    0,
                    100,
                    PropertyHelper.PRO_HEALTH,
                    "",
                    ""
                )
            }
            EquipmentHelper.PART_ARMOR -> {
                EquipmentVo(
                    "寂灭盾牌",
                    "1_normal/armor.png",
                    100,
                    EquipmentHelper.PART_ARMOR,
                    "333333",
                    0,
                    100,
                    PropertyHelper.PRO_DEFENSE,
                    "",
                    ""
                )
            }
            EquipmentHelper.PART_SHOES -> {
                EquipmentVo(
                    "寂灭之靴",
                    "1_normal/shoes.png",
                    100,
                    EquipmentHelper.PART_SHOES,
                    "444444",
                    0,
                    100,
                    PropertyHelper.PRO_SPEED,
                    "",
                    ""
                )
            }
            EquipmentHelper.PART_RING -> {
                EquipmentVo(
                    "寂灭戒指",
                    "1_normal/ring.png",
                    100,
                    EquipmentHelper.PART_RING,
                    "555555",
                    0,
                    100,
                    PropertyHelper.PRO_CRITICAL,
                    "",
                    ""
                )
            }
            EquipmentHelper.PART_NECKLACE -> {
                EquipmentVo(
                    "寂灭项链",
                    "1_normal/necklace.png",
                    100,
                    EquipmentHelper.PART_NECKLACE,
                    "555555",
                    0,
                    100,
                    PropertyHelper.PRO_CRITICAL,
                    "",
                    ""
                )
            }
            EquipmentHelper.PART_AID -> {
                EquipmentVo(
                    "寂灭徽章",
                    "1_normal/aid.png",
                    100,
                    EquipmentHelper.PART_AID,
                    "666666",
                    0,
                    100,
                    PropertyHelper.PRO_CRITICAL,
                    "",
                    ""
                )
            }
            else -> {
                EquipmentVo(
                    "武器",
                    "1_normal/weapon.png",
                    100,
                    EquipmentHelper.PART_WEAPON,
                    "111111",
                    0,
                    100,
                    PropertyHelper.PRO_ATTACK,
                    "",
                    ""
                )
            }
        }

    }
}