package com.nl.room.source

import com.nl.lib.element.effect.EffectEntity
import com.nl.lib.element.effect.EffectEnum
import com.nl.lib.element.enum.CommonEnum
import com.nl.lib.element.enum.PropertyEnum

object EffectDataSource {

    fun mockEffects(): MutableList<EffectEntity> {
        return mutableListOf(
            // 术法无双
            EffectEntity(
                id = "1000111",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100011",
                relationName = "术法无双I",
                desc = "技能伤害提升15%",
                activeLevel = 3,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.15,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),
            EffectEntity(
                id = "1000112",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100011",
                relationName = "术法无双II",
                desc = "受到的技能伤害减少15%",
                activeLevel = 5,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.15,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 镜花水月
            EffectEntity(
                id = "1000121",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100012",
                relationName = "镜花水月",
                desc = "对全体敌人造成4段伤害，每段伤害为攻击力30%-60%",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.45,
                percentageGrowth = 0.03,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 共时交点
            EffectEntity(
                id = "1000211",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100021",
                relationName = "共时交点I",
                desc = "受到攻击时，有30%概率免疫本次伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.02
            ),
            EffectEntity(
                id = "1000212",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100021",
                relationName = "共时交点II",
                desc = "伤害免疫成功对方全体造成自身防御20%的真实伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMUNITY,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DAMAGE_TRUE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE_TRUE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.2,
                triggerProbabilityGrowth = 0.02
            ),

            // 超脱物外
            EffectEntity(
                id = "1000221",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100022",
                relationName = "超脱物外I",
                desc = "对敌方单体造成自身防御70%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.03
            ),
            EffectEntity(
                id = "1000222",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100022",
                relationName = "超脱物外II",
                desc = "并给自身制造一个自身生命值20%的护盾",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_SHIELD,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 天地意志
            EffectEntity(
                id = "1000311",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100031",
                relationName = "天地意志",
                desc = "被攻击的目标有20%的概率禁止行动一回合",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEFENSE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_ACTION,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.2,
                triggerProbabilityGrowth = 0.02
            ),

            // 寂灭剑雨
            EffectEntity(
                id = "1000321",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "100032",
                relationName = "寂灭剑雨",
                desc = "对敌方全体造成自身攻击力160%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_ACTION,
                effectAction = EffectEnum.EFFECT_MODE_DAMAGE,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.4,
                triggerProbabilityGrowth = 0.02
            ),

            // 绕
            EffectEntity(
                id = "2000111",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200011",
                relationName = "绕I",
                desc = "敌方行动后，30%概率追加一次攻击",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ACTION_OTHER,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_ACTION,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.03
            ),
            EffectEntity(
                id = "2000112",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200011",
                relationName = "绕II",
                desc = "对敌方造成自身攻击110%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.1,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 刀光
            EffectEntity(
                id = "2000121",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200012",
                relationName = "刀光",
                desc = "对敌方全体造自身攻击95%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.95,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.02
            ),

            // 豪放不羁
            EffectEntity(
                id = "2000211",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200021",
                relationName = "豪放不羁",
                desc = "每回合增加自身2%攻击力",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ROUND_START,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_ATTACK,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.02,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 破坏真诀
            EffectEntity(
                id = "2000221",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200022",
                relationName = "破坏真诀",
                desc = "对敌方单体造成自身攻击力50%的真实伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_ATTACK,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE_TRUE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.5,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 星卜
            EffectEntity(
                id = "2000311",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200031",
                relationName = "星卜I",
                desc = "首次被击败后利用星辰之力复活",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEATH,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_REVIVE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),
            EffectEntity(
                id = "2000312",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200031",
                relationName = "星卜II",
                desc = "恢复自身40%生命",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEATH,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_HEALTH,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.4,
                percentageGrowth = 0.2,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 0.0
            ),

            // 星罗棋布
            EffectEntity(
                id = "2000321",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200032",
                relationName = "星罗棋布",
                desc = "对敌方前排造成自身攻击160%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.6,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 宿命
            EffectEntity(
                id = "2000411",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200041",
                relationName = "宿命",
                desc = "命运之力缠绕使阿萝有30%几率闪避敌人的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEFENSE,
                priority = EffectEnum.EFFECT_PRIORITY_MIDDLE,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_REVIVE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 会心一击
            EffectEntity(
                id = "2000421",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200042",
                relationName = "会心一击",
                desc = "对敌方后排造成自身攻击120%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.2,
                percentageGrowth = 0.1,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 元力
            EffectEntity(
                id = "2000511",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200051",
                relationName = "元力I",
                desc = "增加自身15%生命",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_HEALTH,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.15,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),
            EffectEntity(
                id = "2000512",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200051",
                relationName = "元力II",
                desc = "增加自身15%防御",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DEFENSE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.15,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 孤注一掷
            EffectEntity(
                id = "2000521",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200052",
                relationName = "孤注一掷I",
                desc = "消耗10%自身生命值",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_HEALTH,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_DEBUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.01,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),
            EffectEntity(
                id = "2000522",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200052",
                relationName = "孤注一掷II",
                desc = "敌方前排损失该生命消耗2倍的生命",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 2.0,
                percentageGrowth = 0.1,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 孤傲龙王
            EffectEntity(
                id = "2000611",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200061",
                relationName = "孤傲龙王",
                desc = "攻击增加30%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.3,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 刀气
            EffectEntity(
                id = "2000621",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200062",
                relationName = "刀气",
                desc = "对敌方全体造成攻击115%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.15,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 浮光掠影
            EffectEntity(
                id = "2000711",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200071",
                relationName = "浮光掠影",
                desc = "被攻击时有30%的几率闪避敌人的攻击",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEFENSE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_DODGE,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.02
            ),

            // 璀璨光华
            EffectEntity(
                id = "2000721",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200072",
                relationName = "璀璨光华",
                desc = "对闪避值低于自身的敌人造成闪避差值*2的真实伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DODGE,
                effectTarget = PropertyEnum.PRO_DAMAGE_TRUE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE_TRUE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_DODGE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 2.0,
                percentageGrowth = 0.2,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 沙脉
            EffectEntity(
                id = "2000811",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200081",
                relationName = "沙脉",
                desc = "受到攻击时有30%的概率减少60%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_DEBUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.6,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.02
            ),

            // 沙咒
            EffectEntity(
                id = "2000821",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200082",
                relationName = "沙咒I",
                desc = "对敌人造成80%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.2,
                percentageGrowth = 0.1,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),
            EffectEntity(
                id = "2000822",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200082",
                relationName = "沙咒II",
                desc = "20%概率使敌人无法行动一回合",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_NULL,
                effectTarget = PropertyEnum.PRO_NULL,
                effectMode = EffectEnum.EFFECT_MODE_ACTION,
                effectAction = EffectEnum.EFFECT_ACTION_DEBUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.0,
                percentageGrowth = 0.0,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.2,
                triggerProbabilityGrowth = 0.01
            ),

            // 脉经
            EffectEntity(
                id = "2000911",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200091",
                relationName = "脉经I",
                desc = "增加自身10攻击",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_ATTACK,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),
            EffectEntity(
                id = "2000912",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200091",
                relationName = "脉经II",
                desc = "增加自身10%防御",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DEFENSE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 海上明月
            EffectEntity(
                id = "2000921",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200092",
                relationName = "海上明月",
                desc = "对敌方后排造成自身攻击140%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.2,
                percentageGrowth = 0.1,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 易形残玄
            EffectEntity(
                id = "2001011",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200101",
                relationName = "易形残玄",
                desc = "每损失5%生命值提升对敌方造成的伤害增加10%",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 龙象般若
            EffectEntity(
                id = "2001021",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200102",
                relationName = "龙象般若",
                desc = "对地方前排造成自身攻击150%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.5,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 时光之咒
            EffectEntity(
                id = "2001111",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200111",
                relationName = "时光之咒I",
                desc = "自身攻击提高10%",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_HEALTH,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),
            EffectEntity(
                id = "2001112",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200111",
                relationName = "时光之咒II",
                desc = "自身防御提高10%",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_ATTACK,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),
            EffectEntity(
                id = "2001113",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200111",
                relationName = "时光之咒III",
                desc = "自身生命提高10%",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_IMMEDIATE,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DEFENSE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.1,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 天道刑法
            EffectEntity(
                id = "2001121",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "200112",
                relationName = "天道刑法",
                desc = "对敌方生命值最低的两名敌人造成自身攻击135%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_HEALTH_LOW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.35,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 执念
            EffectEntity(
                id = "3000111",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300011",
                relationName = "执念",
                desc = "每损失5%生命值提升自身5%攻击力",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_ATTACK,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.05,
                percentageGrowth = 0.01,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 弦线
            EffectEntity(
                id = "3000121",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300012",
                relationName = "弦线",
                desc = "对敌方后排造成自身攻击150%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.5,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 莲心眼
            EffectEntity(
                id = "3000211",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300021",
                relationName = "莲心眼",
                desc = "攻击无视敌方20%防御力",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DEFENSE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_DEBUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 2.0,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 弱水出鞘
            EffectEntity(
                id = "3000221",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300022",
                relationName = "弱水出鞘",
                desc = "对敌方全体造成自身攻击105%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 1.05,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 流光金甲
            EffectEntity(
                id = "3000311",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300031",
                relationName = "流光金甲I",
                desc = "受到攻击时，减少20%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_DEFENSE,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_DEBUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 2.0,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),
            EffectEntity(
                id = "3000312",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300031",
                relationName = "流光金甲II",
                desc = "将最终承受伤害的20%反弹给攻击者",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 脉经盾
            EffectEntity(
                id = "3000321",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300032",
                relationName = "脉经盾",
                desc = "给同行队友(包括自身)制造一个自身生命值20%的护盾",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_SHIELD,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_SELF,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 天命蝎尾
            EffectEntity(
                id = "3000411",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300041",
                relationName = "天命蝎尾",
                desc = "对目标周围敌人造成自身攻击20%的溅射伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_AROUND,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 丹蝎九尾
            EffectEntity(
                id = "3000421",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300042",
                relationName = "丹蝎九尾",
                desc = "对敌方单体造成5段攻击，每段攻击造成自身攻击40%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_ATTACK,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_SINGLE,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 2.0,
                percentageGrowth = 0.2,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 天生沙脉
            EffectEntity(
                id = "3000511",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300051",
                relationName = "天生沙脉",
                desc = "受到攻击时对攻击方造成自身防御力20%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_HIGH,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_AROUND,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 时光之沙
            EffectEntity(
                id = "3000521",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300052",
                relationName = "时光之沙",
                desc = "对敌方全体造成自身防御70%的伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_DEFENSE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ALL,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.7,
                percentageGrowth = 0.05,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),

            // 诡诈
            EffectEntity(
                id = "3000611",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300061",
                relationName = "诡诈",
                desc = "受到攻击时50%几率减免80%伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_INJURED,
                priority = EffectEnum.EFFECT_PRIORITY_MIDDLE,
                effectFrom = PropertyEnum.PRO_DAMAGE,
                effectTarget = PropertyEnum.PRO_DAMAGE,
                effectMode = EffectEnum.EFFECT_MODE_PROPERTY,
                effectAction = EffectEnum.EFFECT_ACTION_BUFF,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_AROUND,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.2,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 1.0,
                triggerProbabilityGrowth = 1.0
            ),

            // 垂死坚持
            EffectEntity(
                id = "3000621",
                relationType = CommonEnum.OBJECT_SKILL,
                relationId = "300062",
                relationName = "垂死坚持",
                desc = "对方后排造成自身生命值30%真实伤害",
                activeLevel = 1,
                isActive = false,
                effectTiming = EffectEnum.EFFECT_TIMING_ATTACK,
                priority = EffectEnum.EFFECT_PRIORITY_NORMAL,
                effectFrom = PropertyEnum.PRO_HEALTH,
                effectTarget = PropertyEnum.PRO_DAMAGE_TRUE,
                effectMode = EffectEnum.EFFECT_MODE_DAMAGE_TRUE,
                effectAction = EffectEnum.EFFECT_ACTION_NULL,
                effectObject = EffectEnum.EFFECT_OBJECT_OTHERS,
                effectScope = EffectEnum.EFFECT_SCOPE_ROW,
                effectType = EffectEnum.EFFECT_TYPE_PERCENTAGE,
                percentage = 0.3,
                percentageGrowth = 0.02,
                value = 0,
                valueGrowth = 0,
                triggerProbability = 0.3,
                triggerProbabilityGrowth = 0.2
            ),
        )
    }
}